# Generated by Django 4.0.4 on 2022-08-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_message_related_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='roomname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
